name: nakimemo
description: A simple crying log app
publish_to: 'none'
version: 1.0.0+3

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  home_widget: ^0.6.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9
  fl_chart: ^0.63.0
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.8.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.1
  csv: ^5.0.2
  path_provider: ^2.1.2
  permission_handler: ^11.0.0
  share_plus: ^7.0.2
  flutter_launcher_icons: ^0.13.1
  google_mobile_ads: ^4.0.0
  intro_slider: ^3.0.10
  in_app_purchase: ^3.1.5
  google_fonts: ^4.0.4
  firebase_core: ^3.13.1
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.5.4
  google_sign_in: ^6.2.1

flutter:
  uses-material-design: true
  generate: true
  assets:
  - .env
  - lib/assets/intro1.png
  - lib/assets/intro2.png
  - lib/assets/intro3.png
  - lib/assets/intro4.png
  - lib/assets/intro5.png
  - lib/assets/intro6.png
  - lib/assets/google_logo.png

flutter_icons:
  android: true
  ios : false
  image_path: "lib/assets/nakimemo.png"
  adaptive_icon_background: "#FFFFFF" # 背景色
  adaptive_icon_foreground: "lib/assets/nakimemo.png" # 前景画像